apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: static-site
          image: "{{ .Values.staticSite.image.repository }}:{{ .Values.staticSite.image.tag }}"
          imagePullPolicy: {{ .Values.staticSite.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
          - name: DB_HOST
            value: {{ .Values.database.serviceName | quote }}
          - name: DB_NAME
            value: {{ .Values.database.name | quote }}
          - name: DB_USER
            value: {{ .Values.database.user | quote }}
          - name: DB_PASS
            value: {{ .Values.database.password | quote }}
