database:
  serviceName: my-postgres-postgresql
  name: devdb
  user: devuser
  password: devpassword

backend:
  image:
    repository: kazemir1/backend
    tag: "1.0"

staticSite:
  image:
    repository: kazemir1/static-site
    tag: "1.0"
    pullPolicy: IfNotPresent
  service:
    port: 80